ddconfig:
  double_z: True
  z_channels: 16
  resolution: 256
  in_channels: 3
  out_ch: 3
  ch: 128
  ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
  num_res_blocks: 2
  attn_resolutions: [16]
  dropout: 0.0